- hosts: localhost
  connection: local
  become: true

  vars:
    - user: coffee
  
  roles:
    # - install # Install modules and packages
    - configure # Setup dotfiles with some additional environment config
