# Android Studio 
- name: Install Android Studio 32bits packages
  package:
    name: "{{ android_studio_packages }}"
    state: present
  when: "{{ install_android }}"

- name: Download and extract Android Studio
  unarchive:
    src: "{{ android_studio_download_url }}"
    remote_src: true
    dest: /opt
    owner: root
    group: root
    mode: "0755"
    creates: /opt/android-studio
  when: "{{ install_android }}"

# Gradle
- name: Create gradle dir
  file:
    path: "{{ gradle_base_dir }}"
    state: directory
  when: "{{ install_android }}"

- name: Download and extract gradle
  unarchive:
    src: "{{ gradle_url }}"
    remote_src: true
    dest: "{{ gradle_base_dir }}"
    owner: root
    group: root
    mode: "0755"
    creates: "{{ gradle_binary }}"
  when: "{{ install_android }}"

- name: Add gradle symlink to path
  file:
    src: "{{ gradle_binary }}"
    dest: "{{ gradle_link }}"
    owner: root
    group: root
    state: link
  when: "{{ install_android }}"
