- name: Add user to "docker" group
  user:
    name: "{{ user }}"
    groups:
      - "docker"
    append: true
  when: "{{ install_docker }}"

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ systemd_services }}"
  when: "{{ install_docker }}"