- name: Prepare apt for terraform
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpgecho "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  when: ansible_distribution == 'Ubuntu'

- name: Install terraform
  apt:
    name: terraform
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'