- name: Creates .config dir if not exists
  become: yes
  become_user: "{{ user }}"
  shell:
    cmd: mkdir -p .config
    chdir: /home/{{ user }}

- name: Clone dotfiles from repository
  become: yes
  become_user: "{{ user }}"
  shell:
    cmd: |
      mkdir -p /home/{{ user }}/.ssh/
      ssh-keyscan github.com >> /home/{{ user }}/.ssh/known_hosts
      git init
      git checkout -b {{ dotfiles_branch }}
      git remote add origin {{ dotfiles_repo_url }}
      git fetch origin
      git reset --hard origin/{{ dotfiles_branch }}
    chdir: /home/{{ user }}/.config
    creates: /home/{{ user }}/.config/.gitignore

- name: Link tmux config file
  file:
    src: /home/{{ user }}/.config/.tmux.conf
    dest: /home/{{ user }}/.tmux.conf
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
