- name: Setup git user email
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Setup git user name
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Setup default branch name
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Clone dotfiles from repository
  become: yes
  become_user: "{{ user }}"
  shell:
    cmd: |
      git init
      git checkout -b {{ dotfiles_branch }}
      git remote add origin {{ dotfiles_repo_url }}
      git fetch origin
      git reset --hard origin/{{ dotfiles_branch }}
    chdir: /home/{{ user }}/.config
    creates: /home/{{ user }}/.config/.gitignore