- name: Setup git user email
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Setup git user name
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Setup default branch name
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
