---
- name: Setup git user email
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Setup git user name
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Setup default branch name
  become: yes
  become_user: "{{ user }}"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Clone dotfiles from repository
  become: yes
  become_user: "{{ user }}"
  shell:
    cmd: |
      git init
      git checkout -b fedora
      git remote add origin {{ dotfiles_repo_url }}
      git fetch origin
      git reset --hard origin/fedora
    chdir: /home/{{ user }}/.config
    creates: /home/{{ user }}/.config/.gitignore

- name: change user shell to zsh 
  become: yes
  become_user: "{{ user }}"
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Copy zshenv file
  copy:
    src: "{{ zshenv_source }}"
    dest: /home/{{ user }}/.zshenv

- name: Clone config repos
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ item.repo_url }}"
    dest: "{{ item.dest }}"
  with_items: "{{ git_repos }}"

- name: Create wallpaper dir
  file:
    path: "{{ wallpaper_dir }}"
    state: directory

- name: Download wallpaper
  get_url:
    url: "{{ wallpaper_url }}"
    dest: "{{ wallpaper_path }}"

- name: Define color scheme based on wallpaper
  command: /home/{{ user }}/.config/scripts/chwp {{ wallpaper_path }}

- name: Run neofetch because why not
  command: neofetch
  register: neofetch

- name: Print neofetch output because why not
  debug:
    var: neofetch.stdout_lines
