---
# Setup DNF
- name: Add yum repositories repo
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck }}"
    gpgcheck: true
  when: ansible_distribution == 'Fedora'
  with_items: "{{ yum_repositories }}"

- name: Enable the RPM Fusion repository
  dnf:
    name: "{{ rpm_fusion_packages }}"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Enable Fedora Copr for LXD
  community.general.copr:
    name: "{{ item }}"
  with_items: "{{ copr_projects }}"
  when: ansible_distribution == 'Fedora'

# Install packages and start services
- name: Install packages from package manager
  package:
    name: "{{ package_manage_packages }}"
    state: present

- name: Add user to "docker" group
  user:
    name: "{{ user }}"
    group: "docker"
    append: yes

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ systemd_services }}"

# Pip
- name: Install packages from pip
  package:
    name: "{{ pip_packages }}"
    state: present

# Node.js
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | sh
    creates=/home/{{ user }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}"
    creates=/home/{{ user }}/.nvm/alias

- name: Install packages from npm
  npm:
    name: "{{ npm_packages }}"
    global: true
    state: present

# Android Studio 
- name: Install Android Studio 32bits packages
  package:
    name: "{{ android_studio_packages }}"
    state: present

- name: Download and extract Android Studio
  unarchive:
    src: "{{ android_studio_download_url }}"
    remote_src: true
    dest: /opt
    owner: root
    group: root
    mode: "0755"

# Joplin
- name: Install Joplin
  shell: >
    curl https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | sh
    creates=/home/{{ user }}/.joplin/Joplin.AppImage

# Droidcam
- name: Install pre requisite packages for droidcam
  package:
    name: "{{ droidcam_packages }}"
    state: present

- name: Download and extract Droidcam
  unarchive:
    src: "{{ droidcam_download_url }}"
    remote_src: true
    dest: /opt/droidcam
    owner: root
    group: root
    mode: "0755"

- name: Install droidcam client
  shell: >
    /bin/bash -c "source /opt/droidcam/install-client"

- name: Install droidcam video
  shell: >
    /bin/bash -c "source /opt/droidcam/install-video"

# AWS CLI
- name: Install pre requisite packages for aws cli
  package:
    name: "{{ aws_packages }}"
    state: present

- name: Download and extract aws cli
  unarchive:
    src: "{{ aws_download_url }}"
    remote_src: true
    dest: /opt/aws
    owner: root
    group: root
    mode: "0755"

- name: Install aws cli
  shell: >
    /bin/bash -c "source /opt/aws/install"

# Gradle
- name: Download and extract gradle
  unarchive:
    src: "{{ gradle_url }}"
    remote_src: true
    dest: "{{ gradle_base_dir }}"
    owner: root
    group: root
    mode: "0755"

- name: Add gradle symlink to path
  file:
    src: "{{ gradle_base_dir }}/{{ gradle_extract_dir }}/bin/gradle"
    dest: "{{ gradle_link }}"
    owner: root
    group: root
    state: link
