---
- include_tasks: subtasks/setup_dnf.yml

- include_tasks: subtasks/package_manager.yml

- include_tasks: subtasks/go.yml

- include_tasks: subtasks/node.yml

- include_tasks: subtasks/pip.yml

- include_tasks: subtasks/oh_my_zsh.yml

- include_tasks: subtasks/starship.yml

- include_tasks: subtasks/aws.yml

- include_tasks: subtasks/smug.yml

- include_tasks: subtasks/docker.yml

- include_tasks: subtasks/kubernetes.yml

- include_tasks: subtasks/joplin.yml

- include_tasks: subtasks/android.yml